image:
  repository: docker.io/naslth
  pullPolicy: IfNotPresent

  tag:
    AngularUI: 1.0.0
    ServiceA: 1.0.0
    ServiceB: 1.0.0
    ServiceC: 1.0.0
    ServiceD: 1.0.0
    ServiceE: 1.0.0
    ServiceF: 1.0.0
    ServiceG: 1.0.0
    ServiceH: 1.0.0

autoscaling:
  minReplicas: 2
  maxReplicas: 6

  metrics:
    memory:
      averageUtilization: 75
    cpu:
      averageUtilization: 75

secrets:
  data:
    mongodbConn: your_value_here
    rabbitmqConn: your_value_here

istio:
  hosts:
    ui: your_value_here.com
    api: your_value_here.com

serviceEntry:
  documentdb:
    hosts:
      - your_value_here.amazonaws.com
  amazonmq:
    hosts:
      - your_value_here.amazonaws.com
