apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mongodb-atlas-external-mesh
spec:
  hosts:
    - {{ .Values.serviceEntry.mongoatlas.url }}
  ports:
    - name: mongoatlas
      number: 27017
      protocol: MONGO
  location: MESH_EXTERNAL
  resolution: DNS
