apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloudamqp-external-mesh
spec:
  hosts:
    - {{ .Values.serviceEntry.rabbitmq.url }}
  ports:
    - name: rabbitmq
      number: 5671
      protocol: TCP
  addresses:
    - 35.208.52.147
  location: MESH_EXTERNAL
  resolution: NONE