apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: istio-gateway
spec:
  selector:
    istio: ingressgateway 
  servers:
    # - port:
    #     number: 80
    #     name: http-gateway
    #     protocol: HTTP
    #   hosts:
    #     - {{ .Values.istio.url }}
    - port:
        number: 443
        name: https-gateway
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: naslth-credential
      hosts:
        - {{ .Values.istio.url }}
