apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cloudamqp-external-mesh
spec:
  hosts:
    - {{ .Values.serviceEntry.rabbitmq.url }}
  ports:
    - name: rabbitmq
      number: 5672
      protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE