image:
  repository: docker.io/naslth
  pullPolicy: IfNotPresent

  tag:
    AngularUI: 1.0.0
    ServiceA: 1.0.6
    ServiceB: 1.0.6
    ServiceC: 1.0.9
    ServiceD: 1.0.9
    ServiceE: 1.0.6
    ServiceF: 1.0.9
    ServiceG: 1.0.6
    ServiceH: 1.0.6

autoscaling:
  minReplicas: 1
  maxReplicas: 3

  metrics:
    memory:
      averageUtilization: 75
    cpu:
      averageUtilization: 75

secrets:
  data:
    mongodbConn: bW9uZ29kYitzcnY6Ly9uYXNsdGg6OTAxNUBrOHMtaXN0aW8tbW9uZ28uZnBmY3R6Yy5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9azhzLWlzdGlvLW1vbmdv
    rabbitmqConn: YW1xcDovL3BwbGF1anhoOnBONHdpMHVobFNGQVUyZW5TN0VaVEtXZElYTmhaaDJIQGFsYmF0cm9zcy5ybXEuY2xvdWRhbXFwLmNvbS9wcGxhdWp4aA==

istio:
  url: naslth.myddns.me

serviceEntry:
  mongoatlas:
    url: k8s-istio-mongo.fpfctzc.mongodb.net
  rabbitmq:
    url: albatross.rmq.cloudamqp.com