apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: amazon-mq-external-mesh
  namespace: dev
spec:
  hosts:
    - {{ your_amazon_mq_hostname }}
  ports:
  - name: rabbitmq
    number: 5671
    protocol: TCP
  location: MESH_EXTERNAL
  resolution: NONE
