apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: angular-ui
  namespace: dev
spec:
  hosts:
    - {{ your_ui_hostname }}
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: angular-ui.dev.svc.cluster.local
            subset: v1
            port:
              number: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: service-a
  namespace: dev
spec:
  hosts:
    - {{ your_api_hostname }}
  gateways:
    - istio-gateway
  http:
    - match:
        - uri:
            prefix: /api
      route:
        - destination:
            host: service-a.dev.svc.cluster.local
            subset: v1
            port:
              number: 8080