apiVersion: v1
kind: Service
metadata:
  name: angular-ui
  labels:
    app: angular-ui
    component: ui
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: angular-ui
    component: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui
  labels:
    app: angular-ui
    component: ui
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: angular-ui
      component: ui
      version: v1
  template:
    metadata:
      labels:
        app: angular-ui
        component: ui
        version: v1
    spec:
      containers:
      - name: angular-ui
        image: registry.hub.docker.com/naslth/k8s-istio-angular-web-service:1.0.0
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent #Always
