apiVersion: v1
kind: Service
metadata:
  name: service-e
  labels:
    app: service-e
    component: service
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: service-e
    component: service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-e
  labels:
    app: service-e
    component: service
    version: v1
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: service-e
      component: service
      version: v1
  template:
    metadata:
      labels:
        app: service-e
        component: service
        version: v1
    spec:
      containers:
        - name: service-e
          image: registry.hub.docker.com/naslth/k8s-istio-service-e:1.0.0
          livenessProbe:
            httpGet:
              path: /api/health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: LOG_LEVEL
              value: info
            - name: SERVICE_G_URL
              value: http://service-g.dev.svc.cluster.local:8080
            - name: SERVICE_H_URL
              value: http://service-h.dev.svc.cluster.local:8080
          ports:
            - containerPort: 8080
        imagePullPolicy: IfNotPresent #Always
