apiVersion: v1
kind: Service
metadata:
  name: angular-ui
  labels:
    app: angular-ui
    component: ui
spec:
  ports:
  - name: http
    port: 80
  selector:
    app: angular-ui
    component: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-ui
  labels:
    app: angular-ui
    component: ui
    version: v1
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      app: angular-ui
      component: ui
      version: v1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: angular-ui
        component: ui
        version: v1
    spec:
      containers:
      - name: angular-ui
        image: {{ printf "%s/k8s-istio-angular-web-service:%s" .Values.image.repository .Values.image.tag.AngularUI }}
        resources:
          requests:
            memory: 55Mi
            cpu: 5m
          limits:
            memory: 400Mi
            cpu: 200m
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        ports:
        - containerPort: 80
        imagePullPolicy: {{ .Values.image.pullPolicy }}
