apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: istio-observe-demo
  region: us-east-1
  version: "1.20"
iam:
  withOIDC: true
managedNodeGroups:
  - name: managed-ng-1
    amiFamily: AmazonLinux2
    instanceType: m5.large
    desiredCapacity: 3
    minSize: 2
    maxSize: 5
    volumeSize: 100
    labels:
      role: worker
      stack: reference-app
    tags:
      nodegroup-name: managed-ng-1
      nodegroup-role: worker
    ssh:
      enableSsm: true # use aws ssm instead of ssh - no need to open port 22
    iam:
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        cloudWatch: true
# cloudWatch:
#   clusterLogging:
#     enableTypes: ["*"]
