apiVersion: v1
kind: Secret
metadata:
  name: k8s-istio-service-config
type: Opaque
data:
  mongodb.conn: {{ .Values.secrets.data.mongodbConn }}
  rabbitmq.conn: {{ .Values.secrets.data.rabbitmqConn }}